export const AXIOS_LOGIN_REQUEST = 'AXIOS_LOGIN_REQUEST';
export const AXIOS_LOGIN_SUCCESS = 'AXIOS_LOGIN_SUCCESS';
export const AXIOS_LOGIN_FAILURE = 'AXIOS_LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const AXIOS_LOGIN_CHECK_REQUEST = 'AXIOS_LOGIN_CHECK_REQUEST';
export const AXIOS_LOGIN_CHECK_SUCCESS = 'AXIOS_LOGIN_CHECK_SUCCESS';
export const AXIOS_CHECK_FAILURE = 'AXIOS_CHECK_FAILURE';
export const AXIOS_NETWORK_ERROR = 'AXIOS_NETWORK_ERROR';
